homepage: "https://www.wolfssl.com/"
language: c++
primary_contact: "guidovranken@gmail.com"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - memory
  - undefined
  - dataflow
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/wolfssl/wolfssl'
